### ISSUE TITLE
Regular Expression Escape

### ISSUE THREAD

**Issue by coolaj86** [flatiron/utile#12]
I don't know if you ever have need for this, but I find that I copy and paste this into almost every project I work on:

``` js
function escapeRegExp(str) {
  return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}
```

http://stackoverflow.com/a/6969486/151312

I just never felt the need to push it to npm because it's so simple... yet every time I search SO to find it again. Think it's worthy of inclusion?

**Comment by pksunkara** [comment]
@indexzero Need your opinion here.

**Comment by englercj** [comment]
+1 Just had to write one of these _again_ the other day, in a module that already uses `utile`.

**Comment by yawnt** [comment]
+1
