### ISSUE TITLE
underscoreToCamel and camelToUnderscore

### ISSUE THREAD

**Issue by chjj** [flatiron/utile#15]
These functions originally looked like this: https://gist.github.com/3229094

@AvianFlu and @cronopio just helped identify a problem with the new versions of these functions.

https://github.com/flatiron/utile/blob/master/lib/index.js#L385

``` js
    var k = utile.inflect.underscore(key);
    obj[k] = obj[key];
    delete obj[key];
```

The problem is introduced with that first line there. All the operations on the object, changing properties, is now unconditional. This means that if a key isn't changed by the inflect function, here is what will happen basically:

``` js
    var k = utile.inflect.underscore('foo_bar');
    obj['foo_bar'] = obj['foo_bar'];
    delete obj['foo_bar'];
```

As you can see, the original property gets deleted, but it's also the only property. 

(Another unrelated problem: The new functions also lack the ability to traverse arrays properly.)

**Comment by pksunkara** [comment]
It's fixed. Can you describe the array traversing problem?

**Comment by chjj** [comment]
> It's fixed. Can you describe the array traversing problem?

They are unable to traverse arrays recursively because utile.camelToUnderscore is not called recursively in the case of an array.

The problem here is this line:

``` js
    if (obj[key] && !Array.isArray(obj[key])
      && typeof obj[key] === 'object') {
      utile.camelToUnderscore(obj[key]);
    }
```

This is in contrast to the original, which checks types at the start of the function and is calls itself unconditionally on an iteration: https://github.com/flatiron/utile/blob/underscore_camel/lib/index.js#L379

``` js
utile.camelToUnderscore = function (obj) {
  if (typeof obj !== 'object' || obj === null) {
    return obj;
  }

  if (Array.isArray(obj)) {
    obj.forEach(utile.camelToUnderscore);
    return obj;
  }

  Object.keys(obj).forEach(function (key) {
    if (/[a-z][A-Z]/.test(key)) {
      var k = key.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
      obj[k] = obj[key];
      delete obj[key];
      key = k;
    }
    utile.camelToUnderscore(obj[key]);
  });

  return obj;
};
```

**Comment by cronopio** [comment]
This patch in the tests show the use case of this problem

```
diff --git a/test/utile-test.js b/test/utile-test.js
index d78f2e0..ec91f01 100644
--- a/test/utile-test.js
+++ b/test/utile-test.js
@@ -101,6 +101,7 @@ vows.describe('utile').addBatch({
     },
     "the camelToUnderscore() method": function () {
       var obj = utile.camelToUnderscore({
+        dont_need_change: 'underscoreValue',
         keyWithCamel: {
           andNested: 'values',
           several: [1, 2, 3],
@@ -112,6 +113,7 @@ vows.describe('utile').addBatch({
       assert.isObject(obj.key_with_camel);
       assert.isString(obj.just_one);
       assert.isTrue(obj.key_with_camel.nested_camel);
+      assert.isString(obj.dont_need_change);
     }
   }
 }).export(module);
```
