### ISSUE TITLE
variable called 'native'

### ISSUE THREAD

**Issue by fkhbgm** [flatiron/utile#17]
Hi,
I was deploying a flatiron hello world application to cloud foundry and I gen an error du to a variable called 'native' (which seems to be reserved by chrome v8) in node_modules/flatiron/node_modules/broadway/node_modules/utile/node_modules/i/lib/inflect.js
As I can not find the 'i' module, I decided to submit the issue to it's direct descendent the 'utile' module.
I just renamed the variable to 'n' to make it work correctly.
Thanks,

**Comment by pksunkara** [comment]
Fixed in v0.1.5
