### ISSUE TITLE
Kill this module

### ISSUE THREAD

**Issue by mmalecki** [flatiron/utile#22]
Consider the following:

I need to bump `rimraf` in `haibu`. `haibu` uses `flatiron.common.rimraf`, which comes from `broadway.common.rimraf`, which comes from `utile.rimraf`. `rimraf` had a breaking change. Now, if I have to bump minor version of `uitle` to avoid breaking compatibility. I also have to bump minor version of `broadway`, if I want to use new `utile` version in it. And, if I decide to use new `broadway` in `flatiron`, I need to bump minor version of `flatiron` too. Finally, I can bump `flatiron` version in `haibu`.

If not for this module, I'd just bump `rimraf` version in `haibu`.

**Comment by edef1c** [comment]
+1

**Comment by jcrugzz** [comment]
With fire preferred. +1

**Comment by edef1c** [comment]
To be exact, we need to butcher it. Cut it into small pieces.

**Comment by blakmatrix** [comment]
I'll bring some chairs and some hotdogs, who's bringing the beverages?

**Comment by julianduque** [comment]
:beers:

**Comment by mmalecki** [comment]
Champagne is on me, when we're done.

**Comment by indexzero** [comment]
We should just stop using that pattern then (i.e. don't hoist). That's your problem, it has nothing to do with the module itself.

**Comment by edef1c** [comment]
@indexzero Why are we exposing those things in this module if we're not supposed to be hoisting shit? That's pretty much the point of grab-bag modules like this. (lim t->infinity grabBagModule = hoarders)

**Comment by yawnt** [comment]
@nathan7 people can find it useful even though we don't use it anymore.. i think this issue should be renamed to "remove utile from our codebase as it has become unsuited to our workflow" and then we leave this module alone :D

**Comment by Swaagie** [comment]
I'm still using this module on a regular basis, there is nothing wrong 
with the basic concepts, just our pattern of use.

On 04/26/2013 01:00 PM, yawnt wrote:

> @nathan7 https://github.com/nathan7 people can find it useful even 
> though we don't use it anymore.. i think this issue should be renamed 
> to "remove utile from our codebase as it has become unsuited to our 
> workflow" and leave this module alone :D
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/flatiron/utile/issues/22#issuecomment-17067082.

## 

Kind regards,
Martijn Swaagman

(M) +31612555611
(@) www.martijnswaagman.nl
(T) twitter.com/swaagie
(L) linkedin.com/in/swaagman

**Comment by edef1c** [comment]
I am firmly against `exports.blah = require('blah')` with blah as dependency. With blah as peerDependency it is okay.
depend to use, peerDepend to expose.

**Comment by indexzero** [comment]
![goonies-never-say-die](https://github.com/flatiron/utile/assets/4624/42cb1de8-2b0f-49d7-952a-4624ce4fb0f3)

If a Github issue is closed and no one notices, did it make a sound? 

Hope you are well @mmalecki 🙏
